"""Initial migration

Revision ID: 31522f781a5d
Revises: 
Create Date: 2021-06-27 10:11:33.128116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31522f781a5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cvStorage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('file', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cvStorage')
    # ### end Alembic commands ###
